export default {
  id: 'mid_4a',
  name: '상용한자(중학4/음독찾기)',
  data: [
    { question: '更', answer: ['고칠 경, 다시 갱', 'さら、ふ(ける)、ふ(かす)', 'こう'] },
    { question: '梗', answer: ['곧을 경', '', 'こう'] },
    { question: '硬', answer: ['단단할 경', 'かた(い)', 'こう'] },
    { question: '芯', answer: ['골풀 심', '', 'しん'] },
    { question: '泌', answer: ['물흐를 필, 분비할 비', '', 'ひつ、ひ'] },
    { question: '蜜', answer: ['꿀 밀', '', 'みつ'] },
    { question: '唄', answer: ['염불소리 패', 'うた', ''] },
    { question: '貢', answer: ['바칠 공', 'みつ(ぐ)', 'こう、く'] },
    { question: '鎖', answer: ['쇠사슬 쇄', 'くさり', 'さ'] },
    { question: '賂', answer: ['뇌물 뢰', '', 'ろ'] },
    { question: '賜', answer: ['줄 사', 'たま(わる)', 'し'] },
    { question: '賄', answer: ['뇌물 회', 'まかな(う)', 'わい'] },
    { question: '貫', answer: ['꿸 관, 무게단위 관', 'つらぬ(く)', 'かん'] },
    { question: '潰', answer: ['무너질 궤', 'つぶ(す)、つぶ(れる)', 'かい'] },
    { question: '且', answer: ['또 차, 구차할 차', 'か(つ)', ''] },
    { question: '租', answer: ['세금 조', '', 'そ'] },
    { question: '粗', answer: ['거칠 조', 'あら(い)', 'そ'] },
    { question: '阻', answer: ['막힐 조', 'はば(む)', 'そ'] },
    { question: '狙', answer: ['원숭이 저, 엿볼 저', 'ねら(う)', 'そ'] },
    { question: '宜', answer: ['마땅할 의', 'よろ(しい)', 'ぎ'] },
    { question: '惧', answer: ['두려워할 구', '', 'ぐ'] },
    { question: '韻', answer: ['운치 운', '', 'いん'] },
    { question: '頃', answer: ['잠깐 경, 즈음 경', 'ころ', ''] },
    { question: '傾', answer: ['기울 경', 'かたむ(く)、かたむ(ける)', 'けい'] },
    { question: '煩', answer: ['번거로울 번', 'わずら(う)、わずら(わす)', 'はん、[ぼん]'] },
    { question: '須', answer: ['반드시 수, 수염 수', '', 'す'] },
    { question: '項', answer: ['목 항', '', 'こう'] },
    { question: '頑', answer: ['완고할 완', '', 'がん'] },
    { question: '頒', answer: ['나눌 반', '', 'はん'] },
    { question: '寡', answer: ['적을 과, 과부 과', '', 'か'] },
    { question: '陣', answer: ['진칠 진', '', 'じん'] },
    { question: '軌', answer: ['바퀴자국 궤', '', 'き'] },
    { question: '軟', answer: ['연할 연', 'やわ(らか)、やわ(らかい)', 'なん'] },
    { question: '輝', answer: ['빛날 휘', 'かがや(く)', 'き'] },
    { question: '恵', answer: ['은혜 혜', 'ぬぐ(む)', 'けい、え'] },
    { question: '穂', answer: ['이삭 수', 'ほ', 'すい'] },
    { question: '凍', answer: ['얼 동', 'こお(る)、こご(える)', 'とう'] },
    { question: '棟', answer: ['대들보 동', 'むね、[むな]', 'とう'] },
    { question: '錬', answer: ['단련할 련', '', 'れん'] },
    { question: '陳', answer: ['베풀 진, 묵을 진', '', 'ちん'] },
    { question: '刺', answer: ['찌를 자, 찌를 척', 'さ(す)、さ(さる)', 'し'] },
    { question: '欄', answer: ['난간 란, 테두리 란', '', 'らん'] },
    { question: '疎', answer: ['성길 소, 트일 소, 드물 소', 'うと(い)、うと(む)', 'そ'] },
    { question: '辣', answer: ['매울 랄', '', 'らつ'] },
    { question: '勅', answer: ['칙서 칙', '', 'ちょく'] },
    { question: '頼', answer: ['의지할 뢰', 'たの(む)、たの(もしい)、たよ(る)', 'らい'] },
    { question: '瀬', answer: ['여울 뢰', 'せ', ''] },
    { question: '畏', answer: ['두려워할 외', 'おそ(れる)、かしこ(まる)', 'い'] },
    { question: '塁', answer: ['진 루', '', 'るい'] },
    { question: '畳', answer: ['겹칠 첩', 'たた(む)、たた(み)', 'じょう'] },
    { question: '埋', answer: ['묻을 매', 'う(める)、う(まる)、う(もれる)', 'まい'] },
    { question: '厘', answer: ['리 리', '', 'りん'] },
    { question: '憧', answer: ['동경할 동', 'あこが(れる)', 'しょう、[どう]'] },
    { question: '瞳', answer: ['눈동자 동', 'ひとみ', 'どう'] },
    { question: '鐘', answer: ['쇠북 종', 'かね', 'しょう'] },
    { question: '糧', answer: ['양식 량', 'かて', 'りょう、[ろう]'] },
    { question: '甲', answer: ['갑옷 갑, 첫째 갑', '', 'こう、かん'] },
    { question: '岬', answer: ['곶 갑', 'みさき', ''] },
    { question: '押', answer: ['누를 압', 'お(す)、お(さえる)', 'おう'] },
    { question: '卑', answer: ['낮을 비', 'いや(しい)、いや(しむ)、いや(しめる)', 'ひ'] },
    { question: '碑', answer: ['비석 비', '', 'ひ'] },
    { question: '袖', answer: ['소매 수', 'そで', 'しゅう'] },
    { question: '抽', answer: ['뽑을 추', '', 'ちゅう'] },
    { question: '軸', answer: ['굴대 축', '', 'じく'] },
    { question: '伸', answer: ['펼 신', 'の(びる)、の(ばす)、の(べる)', 'しん'] },
    { question: '紳', answer: ['띠 신', '', 'しん'] },
    { question: '俺', answer: ['나 엄', 'おれ', ''] },
    { question: '菓', answer: ['과자 과', '', 'か'] },
    { question: '裸', answer: ['벗을 라', 'はだか', 'ら'] },
    { question: '彙', answer: ['무리 휘', '', 'い'] },
    { question: '禅', answer: ['고요할 선', '', 'ぜん'] },
    { question: '弾', answer: ['탄알 탄, 튕길 탄', 'ひ(く)、はず(む)、たま', 'だん'] },
    { question: '幅', answer: ['넓이 폭', 'はば', 'ふく'] },
    { question: '苗', answer: ['싹 묘', 'なえ、[なわ]', 'びょう'] },
    { question: '描', answer: ['그릴 묘', 'えが(く)、か(く)', 'びょう'] },
    { question: '猫', answer: ['고양이 묘', 'ねこ', 'びょう'] },
    { question: '畝', answer: ['이랑 무, 이랑 묘', 'うね', ''] },
    { question: '鬼', answer: ['귀신 귀', 'おに', 'き'] },
    { question: '塊', answer: ['덩어리 괴', 'かたまり', 'かい'] },
    { question: '醜', answer: ['추할 추', 'みにく(い)', 'しゅう'] },
    { question: '魂', answer: ['넋 혼', 'たましい', 'こん'] },
    { question: '累', answer: ['여러 루, 자주 루', '', 'るい'] },
    { question: '索', answer: ['찾을 색, 쓸쓸할 삭', '', 'さく'] },
    { question: '杯', answer: ['잔 배', 'さかずき', 'はい'] },
    { question: '杉', answer: ['삼나무 삼', 'すぎ', ''] },
    { question: '床', answer: ['평상 상', 'とこ、ゆか', 'しょう'] },
    { question: '抹', answer: ['없앨 말', '', 'まつ'] },
    { question: '昧', answer: ['어두울 매', '', 'まい'] },
    { question: '魅', answer: ['매혹할 매', '', 'み'] },
    { question: '徐', answer: ['천천히할 서', '', 'じょ'] },
    { question: '塗', answer: ['칠할 도, 길 도', 'ぬ(る)', 'と'] },
    { question: '途', answer: ['길 도', '', 'と'] },
    { question: '麺', answer: ['밀가루 면', '', 'めん'] },
    { question: '峡', answer: ['골짜기 협', '', 'きょう'] },
    { question: '挟', answer: ['낄 협', 'はさ(む)、はさ(まる)', 'きょう'] },
    { question: '狭', answer: ['좁을 협', 'せま(い)、せば(める)、せば(まる)', 'きょう'] },
    { question: '頬', answer: ['뺨 협', 'ほお', ''] },
    { question: '鉢', answer: ['화분 발, 바리때 발', '', 'はち、[はつ]'] }
  ]
}
